"""Canonical, server-owned Class Hall catalogue.

Wave A is the first tester-playable slice.  The catalogue is immutable so
clients and database rows cannot rewrite class identity, lore or starter
rewards at runtime.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from types import MappingProxyType


@dataclass(frozen=True, slots=True)
class ClassHallProfile:
    hall_id: str
    canonical_class_slug: str
    legacy_class_slugs: tuple[str, ...]
    class_name_it: str
    class_proficiency: str
    class_role: str
    hall_name_it: str
    primary_stat: str
    armor_tags: tuple[str, ...]
    weapon_tags: tuple[str, ...]
    hall_master_witness_npc: str
    lore_hook_it: str
    gameplay_style_it: str
    starter_item_slug: str
    starter_item_name_it: str
    starter_effect_id: str
    starter_lore_key: str
    trial_steps: tuple[str, ...]
    wave: str = "A"
    lifecycle: str = "ACTIVE"
    readiness: str = "APPROVED"
    readiness_version: str = "r18.6-wave-a-v1"


_PROFILES = (
    ClassHallProfile(
        hall_id="hall_guerriero",
        canonical_class_slug="guerriero",
        legacy_class_slugs=("warrior",),
        class_name_it="Guerriero",
        class_proficiency="Warrior",
        class_role="Tank",
        hall_name_it="Fortezza d'Acciaio",
        primary_stat="strength",
        armor_tags=("mail", "plate"),
        weapon_tags=("sword", "axe", "hammer", "shield", "spear", "polearm"),
        hall_master_witness_npc="Comandante Aldric del Ferro",
        lore_hook_it="L'acciaio non si spezza. Si tempra.",
        gameplay_style_it="Mischia frontale, scudo e tempra sostenuta.",
        starter_item_slug="iron_sword",
        starter_item_name_it="Lama del Primo Giuramento di Krastlov",
        starter_effect_id="item.krastlov.first_oath",
        starter_lore_key="krastlov",
        trial_steps=("saluta_aldric", "sostieni_la_linea", "pronuncia_il_giuramento"),
    ),
    ClassHallProfile(
        hall_id="hall_ladro",
        canonical_class_slug="ladro",
        legacy_class_slugs=("rogue",),
        class_name_it="Ladro",
        class_proficiency="Rogue",
        class_role="DPS",
        hall_name_it="Loggia dei Sussurri",
        primary_stat="agility",
        armor_tags=("leather",),
        weapon_tags=("dagger", "sword", "crossbow"),
        hall_master_witness_npc="Maestra dei Sussurri Selene",
        lore_hook_it="Un passo taciuto vale più di cento minacce.",
        gameplay_style_it="Assalti agili, colpi critici ed elusione.",
        starter_item_slug="balanced_dagger",
        starter_item_name_it="Pugnale dell'Ultimo Passo di Irthe",
        starter_effect_id="item.irthe.last_step",
        starter_lore_key="irthe",
        trial_steps=("ascolta_selene", "attraversa_senza_traccia", "lascia_il_segno"),
    ),
    ClassHallProfile(
        hall_id="hall_mago",
        canonical_class_slug="mago",
        legacy_class_slugs=("mage",),
        class_name_it="Mago",
        class_proficiency="Mage",
        class_role="DPS",
        hall_name_it="Circolo dei Nove Sigilli",
        primary_stat="intellect",
        armor_tags=("cloth",),
        weapon_tags=("staff", "tome", "focus", "dagger"),
        hall_master_witness_npc="Arcimago Vessel di Memoria",
        lore_hook_it="Ogni sigillo custodisce una domanda più pericolosa della risposta.",
        gameplay_style_it="Incantatore puro, esplosioni arcane e controllo.",
        starter_item_slug="apprentice_staff",
        starter_item_name_it="Bastone della Prima Faglia di Ergolat",
        starter_effect_id="item.ergolat.first_fracture",
        starter_lore_key="ergolat",
        trial_steps=("osserva_il_sigillo", "stabilizza_la_faglia", "incidi_la_memoria"),
    ),
    ClassHallProfile(
        hall_id="hall_paladino",
        canonical_class_slug="paladino",
        legacy_class_slugs=("paladin", "priest"),
        class_name_it="Paladino",
        class_proficiency="Priest",
        class_role="Support",
        hall_name_it="Reliquiario della Luce Fissa",
        primary_stat="faith",
        armor_tags=("cloth",),
        weapon_tags=("staff", "hammer", "focus", "relic"),
        hall_master_witness_npc="Custode Isabeau dell'Alba",
        lore_hook_it="La luce resta quando il voto costa più della vittoria.",
        gameplay_style_it="Cura, protezione e sostegno sacro.",
        starter_item_slug="initiate_robe",
        starter_item_name_it="Veste del Voto Infranto di Halodi",
        starter_effect_id="item.halodi.broken_vow",
        starter_lore_key="halodi",
        trial_steps=("ascolta_isabeau", "proteggi_la_fiamma", "accetta_il_voto"),
    ),
    ClassHallProfile(
        hall_id="hall_cacciatore_di_mostri",
        canonical_class_slug="cacciatore_di_mostri",
        legacy_class_slugs=("ranger",),
        class_name_it="Cacciatore di Mostri",
        class_proficiency="Ranger",
        class_role="DPS",
        hall_name_it="Capanno del Sentiero Selvaggio",
        primary_stat="agility",
        armor_tags=("leather", "mail"),
        weapon_tags=("bow", "crossbow", "sword", "dagger", "spear"),
        hall_master_witness_npc="Vecchio Falconiere Ovyr",
        lore_hook_it="La pista parla soltanto a chi smette di inseguire il rumore.",
        gameplay_style_it="Attacchi a distanza, trappole e conoscenza delle bestie.",
        starter_item_slug="path_bow",
        starter_item_name_it="Arco del Sentiero Muto di Elfwood",
        starter_effect_id="item.elfwood.silent_trail",
        starter_lore_key="elfwood",
        trial_steps=("osserva_ovyr", "leggi_le_tracce", "risparmia_la_preda"),
    ),
    ClassHallProfile(
        hall_id="hall_alchimista",
        canonical_class_slug="alchimista",
        legacy_class_slugs=("alchemist",),
        class_name_it="Alchimista",
        class_proficiency="Alchemist",
        class_role="Support",
        hall_name_it="Distilleria del Vapore Verde",
        primary_stat="intellect",
        armor_tags=("cloth", "leather"),
        weapon_tags=("dagger", "focus", "vial"),
        hall_master_witness_npc="Maestra Distillatrice Ilyra Ottavia",
        lore_hook_it="Un grammo separa cura e veleno.",
        gameplay_style_it="Pozioni, buff, debuff e utility di distillazione.",
        starter_item_slug="hall_alchimista_bilancia_personale",
        starter_item_name_it="Bilancia Personale del Vapore Verde",
        starter_effect_id="item.vaporeverde.measured_drop",
        starter_lore_key="vaporeverde",
        trial_steps=("ascolta_ilyra", "separa_la_goccia", "sigilla_la_bilancia"),
        wave="B",
    ),
    ClassHallProfile(
        hall_id="hall_bardo",
        canonical_class_slug="bardo",
        legacy_class_slugs=("bard",),
        class_name_it="Bardo",
        class_proficiency="Bard",
        class_role="Support",
        hall_name_it="Taverna della Corda Spezzata",
        primary_stat="faith",
        armor_tags=("cloth", "leather"),
        weapon_tags=("instrument", "rapier", "dagger"),
        hall_master_witness_npc="Bardo Maggiore Ambroise",
        lore_hook_it="Una canzone rimasta a metà è un patto.",
        gameplay_style_it="Morale di gruppo, armonie protettive e debuff sonori.",
        starter_item_slug="hall_bardo_fibbia_corda",
        starter_item_name_it="Fibbia della Corda Spezzata",
        starter_effect_id="item.cordaspezzata.missing_note",
        starter_lore_key="cordaspezzata",
        trial_steps=("ascolta_ambroise", "trova_la_nota", "completa_la_canzone"),
        wave="B",
    ),
    ClassHallProfile(
        hall_id="hall_druido",
        canonical_class_slug="druido",
        legacy_class_slugs=("druid",),
        class_name_it="Druido",
        class_proficiency="Druid",
        class_role="Hybrid",
        hall_name_it="Radura del Salice Millenario",
        primary_stat="faith",
        armor_tags=("cloth", "leather"),
        weapon_tags=("staff", "sickle", "totem"),
        hall_master_witness_npc="Druido Anziano Bran del Salice",
        lore_hook_it="La foresta chiede prima di dare.",
        gameplay_style_it="Trasformazione, guarigione naturale e danni elementali.",
        starter_item_slug="hall_druido_scaglia_salice",
        starter_item_name_it="Scaglia del Salice Millenario",
        starter_effect_id="item.salicemillenario.listening_bark",
        starter_lore_key="salicemillenario",
        trial_steps=("segui_bran", "ascolta_il_salice", "accetta_la_scaglia"),
        wave="B",
    ),
    ClassHallProfile(
        hall_id="hall_monaco",
        canonical_class_slug="monaco",
        legacy_class_slugs=("monk",),
        class_name_it="Monaco",
        class_proficiency="Monk",
        class_role="DPS",
        hall_name_it="Cortile della Corda di Cinabro",
        primary_stat="agility",
        armor_tags=("cloth", "leather"),
        weapon_tags=("fist", "staff"),
        hall_master_witness_npc="Monaco Anziano Ren Silenzio",
        lore_hook_it="Il corpo è la prima disciplina.",
        gameplay_style_it="Combo senz'armi, mobilità e recupero tramite disciplina.",
        starter_item_slug="hall_monaco_nastro_cinabro",
        starter_item_name_it="Nastro della Corda di Cinabro",
        starter_effect_id="item.cinabro.unbroken_balance",
        starter_lore_key="cinabro",
        trial_steps=("saluta_ren", "attraversa_la_corda", "annoda_il_nastro"),
        wave="B",
    ),
    ClassHallProfile(
        hall_id="hall_negromante",
        canonical_class_slug="negromante",
        legacy_class_slugs=("necromancer",),
        class_name_it="Negromante",
        class_proficiency="Necromancer",
        class_role="DPS",
        hall_name_it="Ossario del Cerchio Chiuso",
        primary_stat="intellect",
        armor_tags=("cloth",),
        weapon_tags=("staff", "tome", "dagger"),
        hall_master_witness_npc="Necromante Anziano Silas Nomeperduto",
        lore_hook_it="Ciò che è finito continua se sa il proprio nome.",
        gameplay_style_it="Necroenergia, servitori non morti e logoramento.",
        starter_item_slug="hall_negromante_anello_nome",
        starter_item_name_it="Anello del Nome Chiuso",
        starter_effect_id="item.cerchiochiuso.remembered_name",
        starter_lore_key="cerchiochiuso",
        trial_steps=("incontra_silas", "pronuncia_il_nome", "chiudi_il_cerchio"),
        wave="B",
    ),
    ClassHallProfile(
        hall_id="hall_sciamano",
        canonical_class_slug="sciamano",
        legacy_class_slugs=("shaman",),
        class_name_it="Sciamano",
        class_proficiency="Shaman",
        class_role="Hybrid",
        hall_name_it="Capanna dei Tamburi Fermi",
        primary_stat="faith",
        armor_tags=("cloth", "leather"),
        weapon_tags=("staff", "totem", "mace"),
        hall_master_witness_npc="Sciamano Anziano Vaska Tamburo",
        lore_hook_it="Lo spirito non parla, lo spirito ricorda.",
        gameplay_style_it="Cura elementale, spiriti e sostegno totemico.",
        starter_item_slug="hall_sciamano_piuma_tamburi",
        starter_item_name_it="Piuma dei Tamburi Fermi",
        starter_effect_id="item.tamburifermi.spirit_memory",
        starter_lore_key="tamburifermi",
        trial_steps=("ascolta_vaska", "batti_il_tamburo", "lega_la_piuma"),
        wave="B",
    ),
    ClassHallProfile(
        hall_id="hall_cacciatore_del_vuoto",
        canonical_class_slug="cacciatore_del_vuoto",
        legacy_class_slugs=("void_hunter", "warlock"),
        class_name_it="Cacciatore del Vuoto",
        class_proficiency="VoidHunter",
        class_role="DPS",
        hall_name_it="Faro Rovesciato di Onirade",
        primary_stat="intellect",
        armor_tags=("cloth", "leather"),
        weapon_tags=("bow", "crossbow", "focus"),
        hall_master_witness_npc="Cacciatrice del Vuoto Nael di Onirade",
        lore_hook_it="Si caccia ciò che non ha peso.",
        gameplay_style_it="Distanza, dissoluzione e contrasto agli incorporei.",
        starter_item_slug="hall_cacciatore_vuoto_lanterna",
        starter_item_name_it="Lanterna Muta di Onirade",
        starter_effect_id="item.onirade.weightless_reflection",
        starter_lore_key="onirade",
        trial_steps=("segui_nael", "sostieni_il_riflesso", "spegni_la_lanterna"),
        wave="B",
    ),
    ClassHallProfile(
        hall_id="hall_artificiere",
        canonical_class_slug="artificiere",
        legacy_class_slugs=("artificer",),
        class_name_it="Artificiere",
        class_proficiency="Artificer",
        class_role="Support",
        hall_name_it="Officina Fumante di Rame",
        primary_stat="agility",
        armor_tags=("leather", "mail"),
        weapon_tags=("hammer", "crossbow", "focus"),
        hall_master_witness_npc="Capo Artificiere Nolan Vent",
        lore_hook_it="Ciò che si rompe si rifà; ciò che si rifà migliora.",
        gameplay_style_it="Torrette, dispositivi e supporto tecnico.",
        starter_item_slug="hall_artificiere_cacciavite",
        starter_item_name_it="Cacciavite dell'Ingranaggio Salvato",
        starter_effect_id="item.ingranaggiosalvato.eighth_piece",
        starter_lore_key="ingranaggiosalvato",
        trial_steps=("ascolta_nolan", "rimonta_gli_otto_pezzi", "firma_il_cacciavite"),
        wave="C",
    ),
    ClassHallProfile(
        hall_id="hall_cartografo",
        canonical_class_slug="cartografo",
        legacy_class_slugs=("cartographer",),
        class_name_it="Cartografo",
        class_proficiency="Cartographer",
        class_role="Utility",
        hall_name_it="Camera delle Mappe Vive",
        primary_stat="agility",
        armor_tags=("cloth", "leather"),
        weapon_tags=("dagger", "crossbow", "focus"),
        hall_master_witness_npc="Capomastro Cartografo Odran il Mite",
        lore_hook_it="La mappa non descrive, la mappa ricorda.",
        gameplay_style_it="Esplorazione, ricognizione e movimento.",
        starter_item_slug="hall_cartografo_compasso",
        starter_item_name_it="Compasso del Ricordo della Mappa Viva",
        starter_effect_id="item.mappaviva.blind_route",
        starter_lore_key="mappaviva",
        trial_steps=("ascolta_odran", "percorri_al_buio", "disegna_il_ricordo"),
        wave="C",
    ),
    ClassHallProfile(
        hall_id="hall_cronista",
        canonical_class_slug="cronista",
        legacy_class_slugs=("chronicler",),
        class_name_it="Cronista",
        class_proficiency="Chronicler",
        class_role="Support",
        hall_name_it="Scriptorium del Presente Eterno",
        primary_stat="intellect",
        armor_tags=("cloth",),
        weapon_tags=("tome", "focus", "dagger"),
        hall_master_witness_npc="Cronista Maggiore Ambrose di Mnemos",
        lore_hook_it="Ciò che viene scritto oggi accade oggi per sempre.",
        gameplay_style_it="Riscrittura, informazione e sostegno investigativo.",
        starter_item_slug="hall_cronista_penna_presente",
        starter_item_name_it="Penna del Presente Eterno",
        starter_effect_id="item.presenteeterno.exact_line",
        starter_lore_key="presenteeterno",
        trial_steps=("incontra_ambrose", "trascrivi_senza_errore", "firma_il_presente"),
        wave="C",
    ),
    ClassHallProfile(
        hall_id="hall_fabbro_arcano",
        canonical_class_slug="fabbro_arcano",
        legacy_class_slugs=("arcane_smith",),
        class_name_it="Fabbro Arcano",
        class_proficiency="ArcaneSmith",
        class_role="Utility",
        hall_name_it="Fucina degli Anelli Silenti",
        primary_stat="strength",
        armor_tags=("mail", "plate"),
        weapon_tags=("hammer", "axe", "focus"),
        hall_master_witness_npc="Fabbro Anziano Corvus Anello",
        lore_hook_it="Il metallo tace ma ricorda.",
        gameplay_style_it="Infusione, incantamento e utilità runica.",
        starter_item_slug="hall_fabbro_arcano_martello",
        starter_item_name_it="Martello degli Anelli Silenti",
        starter_effect_id="item.anellisilenti.first_rune",
        starter_lore_key="anellisilenti",
        trial_steps=("ascolta_corvus", "incidi_la_runa", "ricevi_il_martello"),
        wave="C",
    ),
    ClassHallProfile(
        hall_id="hall_mercante",
        canonical_class_slug="mercante",
        legacy_class_slugs=("merchant",),
        class_name_it="Mercante",
        class_proficiency="Merchant",
        class_role="Utility",
        hall_name_it="Loggia del Bilico Onesto",
        primary_stat="agility",
        armor_tags=("cloth", "leather"),
        weapon_tags=("rapier", "crossbow", "dagger"),
        hall_master_witness_npc="Prima Mercatrice Yara della Bilancia",
        lore_hook_it="Il prezzo giusto è quello che entrambi accettano.",
        gameplay_style_it="Contratti, scambi e sostegno economico non-premium.",
        starter_item_slug="hall_mercante_bilancia",
        starter_item_name_it="Bilancia del Bilico Onesto",
        starter_effect_id="item.bilicoonesto.fair_weight",
        starter_lore_key="bilicoonesto",
        trial_steps=("ascolta_yara", "stabilisci_il_valore", "accetta_il_bilico"),
        wave="C",
    ),
    ClassHallProfile(
        hall_id="hall_runista",
        canonical_class_slug="runista",
        legacy_class_slugs=("runist",),
        class_name_it="Runista",
        class_proficiency="Runist",
        class_role="Support",
        hall_name_it="Cerchio delle Pietre Incise",
        primary_stat="intellect",
        armor_tags=("cloth", "mail"),
        weapon_tags=("staff", "hammer", "focus"),
        hall_master_witness_npc="Runista Anziano Halvard Nove",
        lore_hook_it="La runa non descrive, la runa impone.",
        gameplay_style_it="Rune d'area, trappole e dissoluzione.",
        starter_item_slug="hall_runista_scalpello",
        starter_item_name_it="Scalpello della Nona Runa",
        starter_effect_id="item.nonaruna.imposed_mark",
        starter_lore_key="nonaruna",
        trial_steps=("ascolta_halvard", "incidi_la_nona_runa", "spezza_il_silenzio"),
        wave="C",
    ),
    ClassHallProfile(
        hall_id="hall_astrologo",
        canonical_class_slug="astrologo",
        legacy_class_slugs=("astrologer",),
        class_name_it="Astrologo",
        class_proficiency="Astrologer",
        class_role="Support",
        hall_name_it="Osservatorio delle Costellazioni Fisse",
        primary_stat="intellect",
        armor_tags=("cloth",),
        weapon_tags=("staff", "focus", "tome"),
        hall_master_witness_npc="Astrologo Maggiore Cassian Vale",
        lore_hook_it="Ciò che è scritto in alto è già accaduto in basso.",
        gameplay_style_it="Previsione, fasi astrali e debuff cosmici.",
        starter_item_slug="hall_astrologo_compasso",
        starter_item_name_it="Compasso Celeste della Tredicesima Tacca",
        starter_effect_id="item.costellazionifisse.thirteenth_mark",
        starter_lore_key="costellazionifisse",
        trial_steps=("segui_cassian", "riconosci_la_costellazione", "segna_la_tacca"),
        wave="D",
    ),
    ClassHallProfile(
        hall_id="hall_burattinaio",
        canonical_class_slug="burattinaio",
        legacy_class_slugs=("puppeteer",),
        class_name_it="Burattinaio",
        class_proficiency="Puppeteer",
        class_role="Support",
        hall_name_it="Teatro dei Fili di Ferro",
        primary_stat="agility",
        armor_tags=("cloth", "leather"),
        weapon_tags=("dagger", "crossbow", "focus"),
        hall_master_witness_npc="Prima Burattinaia Melisandre Corda",
        lore_hook_it="Il filo che tiene è il filo che libera.",
        gameplay_style_it="Marionette, controllo e debuff a distanza.",
        starter_item_slug="hall_burattinaio_mano_ferro",
        starter_item_name_it="Mano di Ferro del Primo Filo",
        starter_effect_id="item.filidiferro.steady_hand",
        starter_lore_key="filidiferro",
        trial_steps=(
            "incontra_melisandre",
            "muovi_la_marionetta",
            "ferma_il_campanello",
        ),
        wave="D",
    ),
    ClassHallProfile(
        hall_id="hall_giocatore_d_azzardo",
        canonical_class_slug="giocatore_d_azzardo",
        legacy_class_slugs=("gambler",),
        class_name_it="Giocatore d'Azzardo",
        class_proficiency="Gambler",
        class_role="Utility",
        hall_name_it="Sala dei Dadi di Ossidiana",
        primary_stat="agility",
        armor_tags=("cloth", "leather"),
        weapon_tags=("dagger", "crossbow", "focus"),
        hall_master_witness_npc="Croupier Perpetuo Sylas Nod",
        lore_hook_it="La sorte è un patto scritto in nero.",
        gameplay_style_it="Rischio controllato, buff e debuff probabilistici.",
        starter_item_slug="hall_giocatore_dadi_ossidiana",
        starter_item_name_it="Dadi del Tredicesimo Impossibile",
        starter_effect_id="item.ossidiana.impossible_thirteen",
        starter_lore_key="ossidiana",
        trial_steps=("saluta_sylas", "lancia_i_dadi", "leggi_la_faccia_invisibile"),
        wave="D",
    ),
    ClassHallProfile(
        hall_id="hall_parassita",
        canonical_class_slug="parassita",
        legacy_class_slugs=("parasite",),
        class_name_it="Parassita",
        class_proficiency="Parasite",
        class_role="DPS",
        hall_name_it="Cripta della Radice Cava",
        primary_stat="endurance",
        armor_tags=("cloth", "leather"),
        weapon_tags=("dagger", "fist", "sickle"),
        hall_master_witness_npc="Parassita Anziana Ada Cava",
        lore_hook_it="Si vive di ciò che si trova.",
        gameplay_style_it="Furto di statistiche, drenaggio e logoramento.",
        starter_item_slug="hall_parassita_fiala_linfa",
        starter_item_name_it="Fiala di Linfa della Radice Cava",
        starter_effect_id="item.radicecava.borrowed_vigor",
        starter_lore_key="radicecava",
        trial_steps=("segui_ada", "riconosci_la_radice", "accetta_la_linfa"),
        wave="D",
    ),
    ClassHallProfile(
        hall_id="hall_pittore",
        canonical_class_slug="pittore",
        legacy_class_slugs=("painter",),
        class_name_it="Pittore",
        class_proficiency="Painter",
        class_role="Utility",
        hall_name_it="Atelier dei Pigmenti Insanguinati",
        primary_stat="intellect",
        armor_tags=("cloth",),
        weapon_tags=("focus", "staff", "dagger"),
        hall_master_witness_npc="Prima Pittrice Genoveva Rosso",
        lore_hook_it="Il colore giusto costa.",
        gameplay_style_it="Immagini viventi, illusioni e ritratti debilitanti.",
        starter_item_slug="hall_pittore_pennello",
        starter_item_name_it="Pennello del Colore Vivo",
        starter_effect_id="item.colorevivo.moving_stroke",
        starter_lore_key="colorevivo",
        trial_steps=("ascolta_genoveva", "mescola_il_pigmento", "anima_la_tela"),
        wave="D",
    ),
    ClassHallProfile(
        hall_id="hall_sognatore",
        canonical_class_slug="sognatore",
        legacy_class_slugs=("dreamer",),
        class_name_it="Sognatore",
        class_proficiency="Dreamer",
        class_role="Utility",
        hall_name_it="Camera dei Sogni Aperti",
        primary_stat="intellect",
        armor_tags=("cloth",),
        weapon_tags=("focus", "tome", "staff"),
        hall_master_witness_npc="Sognatrice Anziana Elyrah dei Nove Sogni",
        lore_hook_it="Il sogno è già accaduto, solo non lo sappiamo.",
        gameplay_style_it="Controllo mentale, presenze oniriche e utilità psichica.",
        starter_item_slug="hall_sognatore_coperta",
        starter_item_name_it="Coperta dei Nove Sogni Aperti",
        starter_effect_id="item.novesogni.waking_memory",
        starter_lore_key="novesogni",
        trial_steps=("segui_elyrah", "attraversa_il_sogno", "ricorda_ogni_dettaglio"),
        wave="D",
    ),
    ClassHallProfile(
        hall_id="hall_cacciatore_del_sangue",
        canonical_class_slug="cacciatore_del_sangue",
        legacy_class_slugs=("blood_hunter",),
        class_name_it="Cacciatore del Sangue",
        class_proficiency="BloodHunter",
        class_role="DPS",
        hall_name_it="Ossario del Cinghiale Bianco",
        primary_stat="strength",
        armor_tags=("leather", "mail"),
        weapon_tags=("axe", "sword", "spear"),
        hall_master_witness_npc="Cacciatore Solitario Grim Rohl",
        lore_hook_it="Il sangue sa dove torna.",
        gameplay_style_it="Emorragia, sostentamento e colpi sulle prede ferite.",
        starter_item_slug="hall_cacciatore_sangue_zanna",
        starter_item_name_it="Zanna del Cinghiale Bianco",
        starter_effect_id="item.cinghialebianco.returning_blood",
        starter_lore_key="cinghialebianco",
        trial_steps=("segui_grim", "leggi_la_traccia_rossa", "solleva_la_zanna"),
        wave="E",
    ),
    ClassHallProfile(
        hall_id="hall_cavaliere_della_morte",
        canonical_class_slug="cavaliere_della_morte",
        legacy_class_slugs=("death_knight",),
        class_name_it="Cavaliere della Morte",
        class_proficiency="DeathKnight",
        class_role="Hybrid",
        hall_name_it="Cripta del Vessillo Nero",
        primary_stat="endurance",
        armor_tags=("mail", "plate"),
        weapon_tags=("sword", "axe", "shield"),
        hall_master_witness_npc="Primo Cavaliere Nero Vaeric Rahn",
        lore_hook_it="La morte è già passata, io la seguo.",
        gameplay_style_it="Tenuta, necroenergia e aura di paura.",
        starter_item_slug="hall_cavaliere_morte_cintura",
        starter_item_name_it="Cintura del Vessillo Nero",
        starter_effect_id="item.vessillonero.unlowered_standard",
        starter_lore_key="vessillonero",
        trial_steps=("incontra_vaeric", "sostieni_il_vessillo", "completa_il_giro"),
        wave="E",
    ),
    ClassHallProfile(
        hall_id="hall_cavaliere_di_draghi",
        canonical_class_slug="cavaliere_di_draghi",
        legacy_class_slugs=("dragon_knight",),
        class_name_it="Cavaliere di Draghi",
        class_proficiency="DragonKnight",
        class_role="DPS",
        hall_name_it="Ariale del Signore delle Fiamme",
        primary_stat="strength",
        armor_tags=("mail", "plate"),
        weapon_tags=("spear", "sword", "shield"),
        hall_master_witness_npc="Signora delle Fiamme Aelor Draconis",
        lore_hook_it="Il drago non si comanda, si accompagna.",
        gameplay_style_it="Assalti montati, fiamma e presenza draconica.",
        starter_item_slug="hall_cavaliere_draghi_redine",
        starter_item_name_it="Redine di Basalto del Patto delle Fiamme",
        starter_effect_id="item.pattofiamme.steady_gaze",
        starter_lore_key="pattofiamme",
        trial_steps=("segui_aelor", "reggi_lo_sguardo", "accetta_la_redine"),
        wave="E",
    ),
)

CLASS_HALLS = MappingProxyType({profile.hall_id: profile for profile in _PROFILES})


def get_class_hall_profile(hall_id: str) -> ClassHallProfile | None:
    return CLASS_HALLS.get((hall_id or "").strip().lower())


def class_hall_choices_public() -> list[dict]:
    from app.class_halls.mechanics import class_mechanic_public
    from app.classes import class_role_for, registry_entry

    choices: list[dict] = []
    for profile in _PROFILES:
        payload = asdict(profile)
        payload.pop("legacy_class_slugs", None)
        payload.pop("starter_item_slug", None)
        payload.pop("starter_effect_id", None)
        payload.pop("starter_lore_key", None)
        # FASE 9B — il ruolo esposto è quello CANONICO del registry
        # (DPS/TANK/HEALER), non la vecchia tassonomia del profilo.
        payload["class_role"] = (
            class_role_for(profile.canonical_class_slug)
            or profile.class_role
        )
        entry = registry_entry(profile.canonical_class_slug)
        if entry is not None:
            payload["class_identity_it"] = entry.class_identity
            payload["class_mechanics_it"] = entry.class_mechanics
            payload["class_strengths_it"] = list(entry.strengths)
            payload["class_emblem"] = entry.emblem
        payload["assignment_requires_trial"] = True
        payload["assignment_requires_confirmation"] = True
        payload["trial_reward_enabled"] = False
        payload["class_mechanic"] = class_mechanic_public(
            profile.canonical_class_slug
        )
        choices.append(payload)
    return choices


__all__ = [
    "CLASS_HALLS",
    "ClassHallProfile",
    "class_hall_choices_public",
    "get_class_hall_profile",
]
