"""Declarative seed payloads for classes, traits, dungeons and items.

Phase 10 — Content Expansion Pack 1:
- Classes: 5 → 12 (added 7)
- Traits: 5 → 30 (added 25)
- Dungeons: 3 → 10 (added 7, original 3 invariant)
- Items: 14 → 80 (added 66, original 14 invariant)

The actual upsert logic lives in `app/seeds/seed_runner.py`.
"""

CLASS_SEED = [
    # ─── Phase 1 original 5 (DO NOT MODIFY) ──────────────────────────────────
    {"slug": "warrior", "name": "Warrior", "role": "Tank",
     "description": "A stalwart front-liner who absorbs punishment so others may strike.",
     "base_strength": 8, "base_agility": 4, "base_intellect": 2,
     "base_endurance": 9, "base_faith": 2},
    {"slug": "rogue", "name": "Rogue", "role": "DPS",
     "description": "A nimble striker who finds the seams between armor plates.",
     "base_strength": 5, "base_agility": 9, "base_intellect": 3,
     "base_endurance": 4, "base_faith": 2},
    {"slug": "mage", "name": "Mage", "role": "DPS",
     "description": "A scholar of the arcane, frail in body but devastating in spell.",
     "base_strength": 2, "base_agility": 4, "base_intellect": 10,
     "base_endurance": 3, "base_faith": 3},
    {"slug": "priest", "name": "Priest", "role": "Healer",
     "description": "A devout channeler whose prayers mend wounds and lift spirits.",
     "base_strength": 2, "base_agility": 3, "base_intellect": 6,
     "base_endurance": 4, "base_faith": 10},
    {"slug": "ranger", "name": "Ranger", "role": "DPS",
     "description": "A keen-eyed scout who strikes from range before the foe closes.",
     "base_strength": 5, "base_agility": 8, "base_intellect": 4,
     "base_endurance": 5, "base_faith": 3},
    # ─── Phase 10: +7 new classes ────────────────────────────────────────────
    {"slug": "paladin", "name": "Paladin", "role": "Tank",
     "description": "A holy guardian whose shield-arm is matched only by their faith. Tank with healing utility.",
     "base_strength": 7, "base_agility": 3, "base_intellect": 2,
     "base_endurance": 7, "base_faith": 6},
    {"slug": "berserker", "name": "Berserker", "role": "DPS",
     "description": "A frenzied warrior who trades defense for devastating two-handed strikes.",
     "base_strength": 10, "base_agility": 5, "base_intellect": 1,
     "base_endurance": 6, "base_faith": 1},
    {"slug": "druid", "name": "Druid", "role": "Healer",
     "description": "A keeper of the wild paths, channeling nature for both mending and assault.",
     "base_strength": 3, "base_agility": 5, "base_intellect": 7,
     "base_endurance": 5, "base_faith": 7},
    {"slug": "necromancer", "name": "Necromancer", "role": "DPS",
     "description": "A scholar of forbidden arts who weaponizes decay and bound spirits.",
     "base_strength": 2, "base_agility": 4, "base_intellect": 10,
     "base_endurance": 4, "base_faith": 1},
    {"slug": "monk", "name": "Monk", "role": "DPS",
     "description": "An ascetic martial artist who turns body and breath into weapons.",
     "base_strength": 5, "base_agility": 9, "base_intellect": 3,
     "base_endurance": 6, "base_faith": 5},
    {"slug": "bard", "name": "Bard", "role": "Support",
     "description": "A traveling minstrel whose songs bolster allies and unnerve foes.",
     "base_strength": 3, "base_agility": 6, "base_intellect": 7,
     "base_endurance": 4, "base_faith": 5},
    {"slug": "assassin", "name": "Assassin", "role": "DPS",
     "description": "A silent killer who waits for the one perfect strike — and never the second.",
     "base_strength": 6, "base_agility": 10, "base_intellect": 4,
     "base_endurance": 3, "base_faith": 1},
]

TRAIT_SEED = [
    # ─── Phase 2 original 5 (DO NOT MODIFY) ──────────────────────────────────
    {"name": "Brave", "description": "Steady under pressure; lends raw strength.",
     "modifier_type": "flat", "affected_stat": "strength",
     "modifier_value": 1.0, "is_positive": True},
    {"name": "Quick Learner", "description": "Soaks up experience faster than peers.",
     "modifier_type": "percent", "affected_stat": "xp_gain",
     "modifier_value": 10.0, "is_positive": True},
    {"name": "Frail", "description": "Weaker constitution; tires sooner.",
     "modifier_type": "flat", "affected_stat": "endurance",
     "modifier_value": -1.0, "is_positive": False},
    {"name": "Sharp Eye", "description": "Spots openings others miss.",
     "modifier_type": "flat", "affected_stat": "agility",
     "modifier_value": 1.0, "is_positive": True},
    {"name": "Devout", "description": "Anchored to a higher calling.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 1.0, "is_positive": True},
    # ─── Phase 10: +25 new traits (mix of stat-modifiers + flavor) ───────────
    # Stat-buffs (use existing modifier patterns: flat/percent on a stat)
    {"name": "Iron-Willed", "description": "Stubborn in the face of pain.",
     "modifier_type": "flat", "affected_stat": "endurance",
     "modifier_value": 2.0, "is_positive": True},
    {"name": "Scholar", "description": "A lifetime of dusty libraries pays off.",
     "modifier_type": "flat", "affected_stat": "intellect",
     "modifier_value": 2.0, "is_positive": True},
    {"name": "Lightfoot", "description": "Moves without a sound.",
     "modifier_type": "flat", "affected_stat": "agility",
     "modifier_value": 2.0, "is_positive": True},
    {"name": "Bull-Strong", "description": "Carries twice their weight without complaint.",
     "modifier_type": "flat", "affected_stat": "strength",
     "modifier_value": 2.0, "is_positive": True},
    {"name": "Blessed", "description": "Born under a kind star.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 2.0, "is_positive": True},
    {"name": "Fast Reader", "description": "Translates scrolls on the fly.",
     "modifier_type": "percent", "affected_stat": "xp_gain",
     "modifier_value": 15.0, "is_positive": True},
    {"name": "Veteran's Eye", "description": "Has seen this fight before. Knows how it ends.",
     "modifier_type": "percent", "affected_stat": "xp_gain",
     "modifier_value": 5.0, "is_positive": True},
    # Stat-debuffs (negative but realistic recruitment outcomes)
    {"name": "Clumsy", "description": "Trips over their own feet at the worst moments.",
     "modifier_type": "flat", "affected_stat": "agility",
     "modifier_value": -1.0, "is_positive": False},
    {"name": "Slow-Witted", "description": "Takes the long way around every problem.",
     "modifier_type": "flat", "affected_stat": "intellect",
     "modifier_value": -1.0, "is_positive": False},
    {"name": "Weak-Armed", "description": "Cannot draw a heavy bow.",
     "modifier_type": "flat", "affected_stat": "strength",
     "modifier_value": -1.0, "is_positive": False},
    {"name": "Faithless", "description": "Has nothing to pray to and knows it.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": -2.0, "is_positive": False},
    {"name": "Sickly", "description": "Catches every cold within a hundred leagues.",
     "modifier_type": "flat", "affected_stat": "endurance",
     "modifier_value": -2.0, "is_positive": False},
    # Flavor traits — descriptive only, modifier_value=0 (no active resolution)
    # These exist for narrative variety; they pass through the seeder unchanged
    # and never affect formulas because their modifier_value is 0.
    {"name": "Tavern-Born", "description": "Knows every drinking song from here to the coast.",
     "modifier_type": "flat", "affected_stat": "agility",
     "modifier_value": 0.0, "is_positive": True},
    {"name": "Storm-Marked", "description": "A childhood lightning strike left a silver scar — and a slight twitch.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 0.0, "is_positive": True},
    {"name": "Sworn Vow", "description": "Bound by an oath only they remember.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 0.0, "is_positive": True},
    {"name": "Wanderer", "description": "Never sleeps in the same town twice.",
     "modifier_type": "flat", "affected_stat": "agility",
     "modifier_value": 0.0, "is_positive": True},
    {"name": "Beast-Friend", "description": "Stray dogs follow them. Wolves do not bite.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 0.0, "is_positive": True},
    {"name": "Stargazer", "description": "Reads omens in the night sky. Usually wrong.",
     "modifier_type": "flat", "affected_stat": "intellect",
     "modifier_value": 0.0, "is_positive": True},
    {"name": "Bandit Past", "description": "Avoids garrisons and pays in coin.",
     "modifier_type": "flat", "affected_stat": "agility",
     "modifier_value": 0.0, "is_positive": False},
    {"name": "Cursed Coin", "description": "Carries a copper coin that always lands heads.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 0.0, "is_positive": False},
    {"name": "Insomniac", "description": "Sleeps two hours a night and is still tired.",
     "modifier_type": "flat", "affected_stat": "endurance",
     "modifier_value": 0.0, "is_positive": False},
    {"name": "Glassmaker's Child", "description": "Smells of furnace soot. Mends arrowheads cleanly.",
     "modifier_type": "flat", "affected_stat": "intellect",
     "modifier_value": 0.0, "is_positive": True},
    {"name": "Salt-Tongued", "description": "Cannot tell a polite story to save their life.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 0.0, "is_positive": False},
    {"name": "Hollow-Eyed", "description": "Saw something they should not have. They will not say.",
     "modifier_type": "flat", "affected_stat": "intellect",
     "modifier_value": 0.0, "is_positive": False},
    {"name": "Twin-Born", "description": "Has a sibling somewhere. Refuses to talk about them.",
     "modifier_type": "flat", "affected_stat": "endurance",
     "modifier_value": 0.0, "is_positive": True},
]

DUNGEON_SEED = [
    # ─── Phase 3 original 3 (DO NOT MODIFY — gates depend on these slugs) ────
    {
        "slug": "goblin-warrens",
        "name": "Goblin Warrens",
        "description": "A damp tunnel network occupied by goblin scavengers and their crude traps.",
        "difficulty": 1,
        "required_team_size": 3,
        "base_duration_seconds": 60,
        "recommended_power": 45,
        "base_gold_reward": 35,
        "base_xp_reward": 25,
    },
    {
        "slug": "shadow-crypts",
        "name": "Shadow Crypts",
        "description": "Ancient burial halls where restless spirits guard forgotten relics.",
        "difficulty": 2,
        "required_team_size": 3,
        "base_duration_seconds": 120,
        "recommended_power": 60,
        "base_gold_reward": 65,
        "base_xp_reward": 50,
    },
    {
        "slug": "dragons-hoard",
        "name": "Dragon's Hoard",
        "description": "A scorched vault beneath a ruined keep, filled with dragonkin guardians and unstable treasure.",
        "difficulty": 3,
        "required_team_size": 3,
        "base_duration_seconds": 300,
        "recommended_power": 80,
        "base_gold_reward": 120,
        "base_xp_reward": 90,
    },
    # ─── Phase 10: +7 new dungeons (2 T1, 3 T2, 2 T3) ────────────────────────
    # Tier 1 — beginner-friendly (45-75s, recommended_power 30-50)
    {
        "slug": "sewer-nest",
        "name": "Sewer Nest",
        "description": "A flooded undercity drain choked with giant rats and a deeply unpleasant smell.",
        "difficulty": 1,
        "required_team_size": 3,
        "base_duration_seconds": 45,
        "recommended_power": 35,
        "base_gold_reward": 25,
        "base_xp_reward": 18,
    },
    {
        "slug": "bandit-hideout",
        "name": "Bandit Hideout",
        "description": "A wooded clearing where deserters carved out a stockade and a bad reputation.",
        "difficulty": 1,
        "required_team_size": 3,
        "base_duration_seconds": 75,
        "recommended_power": 50,
        "base_gold_reward": 45,
        "base_xp_reward": 30,
    },
    # Tier 2 — mid-game (90-150s, recommended_power 55-70)
    {
        "slug": "druid-grove",
        "name": "Corrupted Druid Grove",
        "description": "Once a place of healing; now the trees scream when touched and the wildlife answers.",
        "difficulty": 2,
        "required_team_size": 3,
        "base_duration_seconds": 90,
        "recommended_power": 55,
        "base_gold_reward": 55,
        "base_xp_reward": 42,
    },
    {
        "slug": "cursed-mines",
        "name": "Cursed Mines",
        "description": "Abandoned silver shafts where the picks still ring — but no miners draw breath.",
        "difficulty": 2,
        "required_team_size": 3,
        "base_duration_seconds": 120,
        "recommended_power": 62,
        "base_gold_reward": 70,
        "base_xp_reward": 52,
    },
    {
        "slug": "sunken-library",
        "name": "Sunken Library",
        "description": "A scholar's archive swallowed by a tidewater, its wards still snapping at intruders.",
        "difficulty": 2,
        "required_team_size": 3,
        "base_duration_seconds": 150,
        "recommended_power": 68,
        "base_gold_reward": 80,
        "base_xp_reward": 62,
    },
    # Tier 3 — end-game (180-300s, recommended_power 75-95)
    {
        "slug": "lich-sanctum",
        "name": "Lich's Sanctum",
        "description": "A sealed observatory atop a windless hill. The phylactery is in there. Probably.",
        "difficulty": 3,
        "required_team_size": 3,
        "base_duration_seconds": 180,
        "recommended_power": 75,
        "base_gold_reward": 100,
        "base_xp_reward": 75,
    },
    {
        "slug": "storm-spire",
        "name": "Storm Spire",
        "description": "A black tower where a stormcaller's tantrum has lasted a hundred years.",
        "difficulty": 3,
        "required_team_size": 3,
        "base_duration_seconds": 240,
        "recommended_power": 88,
        "base_gold_reward": 135,
        "base_xp_reward": 100,
    },
]


# ─── Phase 10: Item helper (reduces repetition; not exported) ────────────────
def _item(slug, name, description, item_type, rarity, power_score,
          s=0, a=0, i=0, e=0, f=0):
    return {
        "slug": slug, "name": name, "description": description,
        "item_type": item_type, "rarity": rarity, "power_score": power_score,
        "strength_bonus": s, "agility_bonus": a, "intellect_bonus": i,
        "endurance_bonus": e, "faith_bonus": f, "affects_combat": True,
    }


ITEM_SEED = [
    # ─── Phase 7 original 14 items (DO NOT MODIFY slugs/stats) ───────────────
    {"slug": "rusted-sword", "name": "Rusted Sword",
     "description": "A pitted blade that has seen too many summers.",
     "item_type": "weapon", "rarity": "Common", "power_score": 1,
     "strength_bonus": 1, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 0, "faith_bonus": 0, "affects_combat": True},
    {"slug": "goblin-dagger", "name": "Goblin Dagger",
     "description": "Crude, jagged, and surprisingly effective in a back alley.",
     "item_type": "weapon", "rarity": "Uncommon", "power_score": 2,
     "strength_bonus": 0, "agility_bonus": 2, "intellect_bonus": 0,
     "endurance_bonus": 0, "faith_bonus": 0, "affects_combat": True},
    {"slug": "cracked-staff", "name": "Cracked Staff",
     "description": "A wizard's staff with a hairline fracture; the focus crystal still hums.",
     "item_type": "weapon", "rarity": "Common", "power_score": 1,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 1,
     "endurance_bonus": 0, "faith_bonus": 1, "affects_combat": True},
    {"slug": "novice-charm", "name": "Novice Charm",
     "description": "A small wooden pendant carved with a quiet prayer.",
     "item_type": "accessory", "rarity": "Common", "power_score": 1,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 0, "faith_bonus": 1, "affects_combat": True},
    {"slug": "torn-leather-vest", "name": "Torn Leather Vest",
     "description": "Patched in three places. Still keeps the cold off.",
     "item_type": "armor", "rarity": "Common", "power_score": 1,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 1, "faith_bonus": 0, "affects_combat": True},
    {"slug": "cryptbone-blade", "name": "Cryptbone Blade",
     "description": "A jagged shortsword carved from a barrow-wight's femur. It hums with old anger.",
     "item_type": "weapon", "rarity": "Rare", "power_score": 4,
     "strength_bonus": 3, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 1, "faith_bonus": 0, "affects_combat": True},
    {"slug": "spiritglass-staff", "name": "Spiritglass Staff",
     "description": "A staff topped with a sliver of soulglass. It whispers at the edge of hearing.",
     "item_type": "weapon", "rarity": "Rare", "power_score": 4,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 3,
     "endurance_bonus": 0, "faith_bonus": 1, "affects_combat": True},
    {"slug": "gravewarden-mail", "name": "Gravewarden Mail",
     "description": "Rust-pitted but resilient — armor pulled from a tomb-knight that refused to fall twice.",
     "item_type": "armor", "rarity": "Rare", "power_score": 4,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 4, "faith_bonus": 0, "affects_combat": True},
    {"slug": "relic-signet", "name": "Relic Signet",
     "description": "A signet ring inlaid with a smoky relic-shard. Whoever wore it last is not coming back for it.",
     "item_type": "accessory", "rarity": "Rare", "power_score": 3,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 1,
     "endurance_bonus": 0, "faith_bonus": 2, "affects_combat": True},
    {"slug": "drakefang-greatsword", "name": "Drakefang Greatsword",
     "description": "A two-hander forged around the fang of a young dragon. The blade smokes when drawn.",
     "item_type": "weapon", "rarity": "Epic", "power_score": 7,
     "strength_bonus": 5, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 2, "faith_bonus": 0, "affects_combat": True},
    {"slug": "embermind-focus", "name": "Embermind Focus",
     "description": "A wand of dragonbone bound in copper wire. Channels heat like a furnace.",
     "item_type": "weapon", "rarity": "Epic", "power_score": 7,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 5,
     "endurance_bonus": 0, "faith_bonus": 2, "affects_combat": True},
    {"slug": "dragonscale-vest", "name": "Dragonscale Vest",
     "description": "Overlapping scales stitched onto cured leather. Light, hot to the touch, hard as stone.",
     "item_type": "armor", "rarity": "Epic", "power_score": 6,
     "strength_bonus": 0, "agility_bonus": 1, "intellect_bonus": 0,
     "endurance_bonus": 5, "faith_bonus": 0, "affects_combat": True},
    {"slug": "hoardlords-seal", "name": "Hoardlord's Seal",
     "description": "A heavy gold amulet shaped like a coiled wyrm. It seems to weigh the wearer down — yet they walk taller.",
     "item_type": "accessory", "rarity": "Epic", "power_score": 6,
     "strength_bonus": 2, "agility_bonus": 0, "intellect_bonus": 2,
     "endurance_bonus": 0, "faith_bonus": 2, "affects_combat": True},

    # ─── Phase 10 expansion ──────────────────────────────────────────────────
    # COMMON — weapons (power_score 1, single +1 stat)
    _item("training-shortsword", "Training Shortsword", "Wooden core, leather wrap. Bruises more than it cuts.",
          "weapon", "Common", 1, s=1),
    _item("hunting-knife", "Hunting Knife", "Made for skinning rabbits, repurposed for tighter quarters.",
          "weapon", "Common", 1, a=1),
    _item("apprentice-wand", "Apprentice Wand", "Yew rod, copper tip. Sparks more than it casts.",
          "weapon", "Common", 1, i=1),
    _item("oak-cudgel", "Oak Cudgel", "Thick, knotted, dependable. Favored by tavern bouncers.",
          "weapon", "Common", 1, s=1),
    _item("acolyte-mace", "Acolyte Mace", "A novice's first ceremonial weapon. The head wobbles a bit.",
          "weapon", "Common", 1, f=1),
    _item("scout-shortbow", "Scout Shortbow", "Light draw, fast nock. Good for rabbits and panicked retreats.",
          "weapon", "Common", 1, a=1),
    _item("sling-and-stones", "Sling and Stones", "Free ammunition wherever the road forks.",
          "weapon", "Common", 1, a=1),
    _item("pitchfork", "Pitchfork", "Three tines. Reach is everything when you're outnumbered.",
          "weapon", "Common", 1, s=1),
    # COMMON — armor
    _item("hempcloth-tunic", "Hempcloth Tunic", "Itchy, but cheap and reasonably hard to tear.",
          "armor", "Common", 1, e=1),
    _item("padded-jerkin", "Padded Jerkin", "Quilted layers stop a punch better than nothing.",
          "armor", "Common", 1, e=1),
    _item("travelers-cloak", "Traveler's Cloak", "Smells of woodsmoke. Has hidden pockets.",
          "armor", "Common", 1, e=1),
    _item("apprentice-robe", "Apprentice Robe", "Inkstained sleeves. Helps focus, slightly.",
          "armor", "Common", 1, i=1),
    _item("leather-cap", "Leather Cap", "A little better than nothing falling on your head.",
          "armor", "Common", 1, e=1),
    # COMMON — accessory
    _item("copper-ring", "Copper Ring", "Tarnished. Sized for a peasant.",
          "accessory", "Common", 1, s=1),
    _item("river-pebble-charm", "River-Pebble Charm", "Small, smooth, lucky. Possibly.",
          "accessory", "Common", 1, f=1),
    _item("twine-bracelet", "Twine Bracelet", "Tied at a wayshrine. Faded to grey.",
          "accessory", "Common", 1, f=1),
    _item("herbalist-pouch", "Herbalist's Pouch", "Bundles of dried roots; helps with focus.",
          "accessory", "Common", 1, i=1),

    # UNCOMMON — weapons (power_score 2, +2 single or +1/+1 split)
    _item("iron-arming-sword", "Iron Arming Sword", "Reliable cut, decent reach. The garrison standard.",
          "weapon", "Uncommon", 2, s=2),
    _item("guard-spear", "Guard Spear", "Reach, balance, and a wicked leaf-blade tip.",
          "weapon", "Uncommon", 2, s=1, a=1),
    _item("rangers-bow", "Ranger's Bow", "Longbow staved from yew. Pulls heavy.",
          "weapon", "Uncommon", 2, a=2),
    _item("monk-staff", "Monk Staff", "Hardwood pole, brass caps. Surprisingly fast.",
          "weapon", "Uncommon", 2, a=1, e=1),
    _item("bone-rosary", "Bone Rosary Mace", "Knucklebones strung on a chain. Clatters at every step.",
          "weapon", "Uncommon", 2, f=2),
    _item("hex-rod", "Hex Rod", "Twisted oak. Smells faintly of ozone.",
          "weapon", "Uncommon", 2, i=2),
    _item("duelist-rapier", "Duelist's Rapier", "Thin, precise. Made for finding ribs.",
          "weapon", "Uncommon", 2, a=2),
    _item("warhammer", "Iron Warhammer", "Heavy head, short haft. For shields and skulls.",
          "weapon", "Uncommon", 2, s=2),
    # UNCOMMON — armor
    _item("studded-leather", "Studded Leather", "Iron rivets sewn into thick hide. The classic.",
          "armor", "Uncommon", 2, e=2),
    _item("chainmail-shirt", "Chainmail Shirt", "Tight rings, heavier than it looks. Worth it.",
          "armor", "Uncommon", 2, e=2),
    _item("wardens-cloak", "Warden's Cloak", "Field-issue, oilcloth lined. Sheds rain and arrows alike.",
          "armor", "Uncommon", 2, e=1, a=1),
    _item("acolyte-vestments", "Acolyte Vestments", "Embroidered with the lesser prayers. Light, durable.",
          "armor", "Uncommon", 2, f=2),
    _item("scout-leathers", "Scout Leathers", "Cut for sprinting. The hood pulls forward like a bird's beak.",
          "armor", "Uncommon", 2, a=2),
    # UNCOMMON — accessory
    _item("silver-pendant", "Silver Pendant", "A pilgrim's keepsake. Cool to the touch.",
          "accessory", "Uncommon", 2, f=2),
    _item("ironband-ring", "Ironband Ring", "A soldier's wedding band. Lent strength to whoever wore it last.",
          "accessory", "Uncommon", 2, s=2),
    _item("luck-coin", "Bandit's Luck Coin", "A copper coin worn smooth by nervous thumbs.",
          "accessory", "Uncommon", 2, a=2),
    _item("scholars-spectacles", "Scholar's Spectacles", "Cracked lens on the left. Still useful.",
          "accessory", "Uncommon", 2, i=2),
    _item("bonded-amulet", "Bonded Amulet", "Two halves welded together. Strong against fear.",
          "accessory", "Uncommon", 2, e=2),

    # RARE — weapons (power_score 4, +3/+1 split or +3 single + 1 split)
    _item("warden-longsword", "Warden's Longsword", "The captain's blade — fluted steel, leather-wrapped grip.",
          "weapon", "Rare", 4, s=3, e=1),
    _item("moonsilver-bow", "Moonsilver Bow", "Drawn it sings. The arrows hum after release.",
          "weapon", "Rare", 4, a=3, i=1),
    _item("warlocks-grimoire", "Warlock's Grimoire", "A handheld tome, half-stitched in living shadow.",
          "weapon", "Rare", 4, i=3, f=1),
    _item("oathkeeper-mace", "Oathkeeper Mace", "Engraved with a vow only the wielder can read.",
          "weapon", "Rare", 4, f=3, s=1),
    _item("whisperblade", "Whisperblade", "Cuts cloth before it cuts skin. Quiet as snowfall.",
          "weapon", "Rare", 4, a=3, s=1),
    # RARE — armor
    _item("steel-half-plate", "Steel Half-Plate", "Solid breastplate, articulated arms. A knight's working kit.",
          "armor", "Rare", 4, e=3, s=1),
    _item("druids-bark-mantle", "Druid's Bark Mantle", "Living bark woven into a cloak. Heals slowly when worn.",
          "armor", "Rare", 4, e=2, f=2),
    _item("sapper-coat", "Sapper's Coat", "Reinforced against splinters and worse.",
          "armor", "Rare", 4, e=3, a=1),
    # RARE — accessory
    _item("captains-signet", "Captain's Signet", "Stamped with a regiment that no longer exists.",
          "accessory", "Rare", 3, s=2, e=1),
    _item("seers-monocle", "Seer's Monocle", "Tinted glass shows things just before they happen.",
          "accessory", "Rare", 3, i=2, f=1),
    _item("oracle-pendant", "Oracle Pendant", "Tongue of a long-dead serpent. Counsels in dreams.",
          "accessory", "Rare", 3, i=1, f=2),

    # EPIC — weapons (power_score 6-7, multi-stat)
    _item("frostfang-claymore", "Frostfang Claymore", "The blade weeps water that freezes on contact.",
          "weapon", "Epic", 7, s=5, e=2),
    _item("voidpiercer-bow", "Voidpiercer Bow", "Draws on stillness itself. Arrows pass through ghosts.",
          "weapon", "Epic", 6, a=4, i=2),
    _item("archmagi-staff", "Archmagi Staff", "A staff bound with seven sealing rings. The runes glow when angry.",
          "weapon", "Epic", 7, i=5, f=2),
    _item("paragon-warhammer", "Paragon Warhammer", "Forged in a chapel forge. Hums softly when held by the worthy.",
          "weapon", "Epic", 7, s=5, f=2),
    _item("shadowedge", "Shadowedge", "A curved blade so dark it bends torchlight around it.",
          "weapon", "Epic", 7, a=5, s=2),
    # EPIC — armor
    _item("stormforged-plate", "Stormforged Plate", "Steel quenched in lightning. Smells of ozone for centuries.",
          "armor", "Epic", 6, e=5, s=1),
    _item("aether-weave-robe", "Aether-Weave Robe", "Threads spun from captured sky. Light as breath.",
          "armor", "Epic", 6, e=2, i=4),
    # EPIC — accessory
    _item("crown-of-stillness", "Crown of Stillness", "A thin silver circlet. Wearers sleep without dreaming.",
          "accessory", "Epic", 6, i=3, f=3),
    _item("everwarm-pendant", "Everwarm Pendant", "A blood-red stone that burns without heat. Cannot be put down.",
          "accessory", "Epic", 6, f=3, e=3),

    # ─── Phase 10 fill-up to hit ≥80 (9 Common + 3 Uncommon) ────────────────
    _item("training-buckler", "Training Buckler", "A small wooden shield, scarred from years of drill.",
          "armor", "Common", 1, e=1),
    _item("woolen-mantle", "Woolen Mantle", "Warm, scratchy, smells faintly of the sheep.",
          "armor", "Common", 1, e=1),
    _item("conscripts-helm", "Conscript's Helm", "A pot-helm pressed from cheap steel. Better than no helm.",
          "armor", "Common", 1, e=1),
    _item("torchbearer-cloak", "Torchbearer Cloak", "Soaked in pitch and lamp oil. Smells dangerous.",
          "armor", "Common", 1, e=1),
    _item("apprentice-handbook", "Apprentice Handbook", "Half-finished spell notes in a stained satchel.",
          "accessory", "Common", 1, i=1),
    _item("road-walkers-staff", "Road-Walker's Staff", "More walking aid than weapon. Still has a knot like a fist.",
          "weapon", "Common", 1, a=1),
    _item("rough-flail", "Rough Flail", "Knotted chain on a wooden grip. Awkward but mean.",
          "weapon", "Common", 1, s=1),
    _item("driftwood-charm", "Driftwood Charm", "Smoothed by sea-salt. Floats in any cup of water.",
          "accessory", "Common", 1, f=1),
    _item("traveler-amulet", "Traveler's Amulet", "Cheap tin disc stamped with a half-faded saint.",
          "accessory", "Common", 1, f=1),
    _item("steelweave-gauntlets", "Steelweave Gauntlets", "Mail-and-leather gloves. Steady the grip.",
          "armor", "Uncommon", 2, s=1, e=1),
    _item("songsteel-flute", "Songsteel Flute", "A bardic instrument with a hidden razor edge.",
          "weapon", "Uncommon", 2, a=1, i=1),
    _item("warding-bracer", "Warding Bracer", "Iron bracer engraved with old protective runes.",
          "accessory", "Uncommon", 2, e=1, f=1),
]
