"""Declarative seed payloads for classes, traits, dungeons and items.

These are pure data. The actual upsert logic still lives in `server.py`
(seeding helpers). When Phase 5.5b lands, the seed runner will move into
`app/seeds/seed_runner.py` and consume these payloads directly.
"""

CLASS_SEED = [
    {"slug": "warrior", "name": "Warrior", "role": "Tank",
     "description": "A stalwart front-liner who absorbs punishment so others may strike.",
     "base_strength": 8, "base_agility": 4, "base_intellect": 2,
     "base_endurance": 9, "base_faith": 2},
    {"slug": "rogue", "name": "Rogue", "role": "DPS",
     "description": "A nimble striker who finds the seams between armor plates.",
     "base_strength": 5, "base_agility": 9, "base_intellect": 3,
     "base_endurance": 4, "base_faith": 2},
    {"slug": "mage", "name": "Mage", "role": "DPS",
     "description": "A scholar of the arcane, frail in body but devastating in spell.",
     "base_strength": 2, "base_agility": 4, "base_intellect": 10,
     "base_endurance": 3, "base_faith": 3},
    {"slug": "priest", "name": "Priest", "role": "Healer",
     "description": "A devout channeler whose prayers mend wounds and lift spirits.",
     "base_strength": 2, "base_agility": 3, "base_intellect": 6,
     "base_endurance": 4, "base_faith": 10},
    {"slug": "ranger", "name": "Ranger", "role": "DPS",
     "description": "A keen-eyed scout who strikes from range before the foe closes.",
     "base_strength": 5, "base_agility": 8, "base_intellect": 4,
     "base_endurance": 5, "base_faith": 3},
]

TRAIT_SEED = [
    {"name": "Brave", "description": "Steady under pressure; lends raw strength.",
     "modifier_type": "flat", "affected_stat": "strength",
     "modifier_value": 1.0, "is_positive": True},
    {"name": "Quick Learner", "description": "Soaks up experience faster than peers.",
     "modifier_type": "percent", "affected_stat": "xp_gain",
     "modifier_value": 10.0, "is_positive": True},
    {"name": "Frail", "description": "Weaker constitution; tires sooner.",
     "modifier_type": "flat", "affected_stat": "endurance",
     "modifier_value": -1.0, "is_positive": False},
    {"name": "Sharp Eye", "description": "Spots openings others miss.",
     "modifier_type": "flat", "affected_stat": "agility",
     "modifier_value": 1.0, "is_positive": True},
    {"name": "Devout", "description": "Anchored to a higher calling.",
     "modifier_type": "flat", "affected_stat": "faith",
     "modifier_value": 1.0, "is_positive": True},
]

DUNGEON_SEED = [
    {
        "slug": "goblin-warrens",
        "name": "Goblin Warrens",
        "description": "A damp tunnel network occupied by goblin scavengers and their crude traps.",
        "difficulty": 1,
        "required_team_size": 3,
        "base_duration_seconds": 60,
        "recommended_power": 45,
        "base_gold_reward": 35,
        "base_xp_reward": 25,
    },
    {
        "slug": "shadow-crypts",
        "name": "Shadow Crypts",
        "description": "Ancient burial halls where restless spirits guard forgotten relics.",
        "difficulty": 2,
        "required_team_size": 3,
        "base_duration_seconds": 120,
        "recommended_power": 60,
        "base_gold_reward": 65,
        "base_xp_reward": 50,
    },
    {
        "slug": "dragons-hoard",
        "name": "Dragon's Hoard",
        "description": "A scorched vault beneath a ruined keep, filled with dragonkin guardians and unstable treasure.",
        "difficulty": 3,
        "required_team_size": 3,
        "base_duration_seconds": 300,
        "recommended_power": 80,
        "base_gold_reward": 120,
        "base_xp_reward": 90,
    },
]

ITEM_SEED = [
    {"slug": "rusted-sword", "name": "Rusted Sword",
     "description": "A pitted blade that has seen too many summers.",
     "item_type": "weapon", "rarity": "Common", "power_score": 1,
     "strength_bonus": 1, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 0, "faith_bonus": 0, "affects_combat": True},
    {"slug": "goblin-dagger", "name": "Goblin Dagger",
     "description": "Crude, jagged, and surprisingly effective in a back alley.",
     "item_type": "weapon", "rarity": "Uncommon", "power_score": 2,
     "strength_bonus": 0, "agility_bonus": 2, "intellect_bonus": 0,
     "endurance_bonus": 0, "faith_bonus": 0, "affects_combat": True},
    {"slug": "cracked-staff", "name": "Cracked Staff",
     "description": "A wizard's staff with a hairline fracture; the focus crystal still hums.",
     "item_type": "weapon", "rarity": "Common", "power_score": 1,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 1,
     "endurance_bonus": 0, "faith_bonus": 1, "affects_combat": True},
    {"slug": "novice-charm", "name": "Novice Charm",
     "description": "A small wooden pendant carved with a quiet prayer.",
     "item_type": "accessory", "rarity": "Common", "power_score": 1,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 0, "faith_bonus": 1, "affects_combat": True},
    {"slug": "torn-leather-vest", "name": "Torn Leather Vest",
     "description": "Patched in three places. Still keeps the cold off.",
     "item_type": "armor", "rarity": "Common", "power_score": 1,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 1, "faith_bonus": 0, "affects_combat": True},
    # ─── Phase 7: Shadow Crypts (Rare) ──────────────────────────────────────
    {"slug": "cryptbone-blade", "name": "Cryptbone Blade",
     "description": "A jagged shortsword carved from a barrow-wight's femur. It hums with old anger.",
     "item_type": "weapon", "rarity": "Rare", "power_score": 4,
     "strength_bonus": 3, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 1, "faith_bonus": 0, "affects_combat": True},
    {"slug": "spiritglass-staff", "name": "Spiritglass Staff",
     "description": "A staff topped with a sliver of soulglass. It whispers at the edge of hearing.",
     "item_type": "weapon", "rarity": "Rare", "power_score": 4,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 3,
     "endurance_bonus": 0, "faith_bonus": 1, "affects_combat": True},
    {"slug": "gravewarden-mail", "name": "Gravewarden Mail",
     "description": "Rust-pitted but resilient — armor pulled from a tomb-knight that refused to fall twice.",
     "item_type": "armor", "rarity": "Rare", "power_score": 4,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 4, "faith_bonus": 0, "affects_combat": True},
    {"slug": "relic-signet", "name": "Relic Signet",
     "description": "A signet ring inlaid with a smoky relic-shard. Whoever wore it last is not coming back for it.",
     "item_type": "accessory", "rarity": "Rare", "power_score": 3,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 1,
     "endurance_bonus": 0, "faith_bonus": 2, "affects_combat": True},
    # ─── Phase 7: Dragon's Hoard (Epic) ─────────────────────────────────────
    {"slug": "drakefang-greatsword", "name": "Drakefang Greatsword",
     "description": "A two-hander forged around the fang of a young dragon. The blade smokes when drawn.",
     "item_type": "weapon", "rarity": "Epic", "power_score": 7,
     "strength_bonus": 5, "agility_bonus": 0, "intellect_bonus": 0,
     "endurance_bonus": 2, "faith_bonus": 0, "affects_combat": True},
    {"slug": "embermind-focus", "name": "Embermind Focus",
     "description": "A wand of dragonbone bound in copper wire. Channels heat like a furnace.",
     "item_type": "weapon", "rarity": "Epic", "power_score": 7,
     "strength_bonus": 0, "agility_bonus": 0, "intellect_bonus": 5,
     "endurance_bonus": 0, "faith_bonus": 2, "affects_combat": True},
    {"slug": "dragonscale-vest", "name": "Dragonscale Vest",
     "description": "Overlapping scales stitched onto cured leather. Light, hot to the touch, hard as stone.",
     "item_type": "armor", "rarity": "Epic", "power_score": 6,
     "strength_bonus": 0, "agility_bonus": 1, "intellect_bonus": 0,
     "endurance_bonus": 5, "faith_bonus": 0, "affects_combat": True},
    {"slug": "hoardlords-seal", "name": "Hoardlord's Seal",
     "description": "A heavy gold amulet shaped like a coiled wyrm. It seems to weigh the wearer down — yet they walk taller.",
     "item_type": "accessory", "rarity": "Epic", "power_score": 6,
     "strength_bonus": 2, "agility_bonus": 0, "intellect_bonus": 2,
     "endurance_bonus": 0, "faith_bonus": 2, "affects_combat": True},
]
